apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: nginx:latest              
          securityContext:
            privileged: true                
            runAsUser: 0                    # high: running as root
            allowPrivilegeEscalation: true   
          resources: {}                     
          ports:
            - containerPort: 80
          env:
            - name: DB_PASSWORD
              value: "hardcoded-secret-123"  
---
apiVersion: v1
kind: Service
metadata:
  name: web-app-svc
spec:
  type: LoadBalancer                          
  selector:
    app: web-app
  ports:
    - port: 80
